os:
  - linux
  # - osx

language: cpp

dist: trusty
sudo: require

compiler:
    - g++-4.8
    - clang-3.6

addons:
    apt:
        sources:
            # add PPAs with more up-to-date toolchains
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
        packages:
            # - liblog4cplus-dev
            - libboost-dev
            - libboost-python-dev

before_install:
    - wget https://launchpad.net/ubuntu/+archive/primary/+files/liblog4cplus-dev_1.1.2-3.2_i386.deb
    - sudo dpkg -i liblog4cplus-dev_1.1.2-3.2_i386.deb

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        mkdir build;
        cd build;
        cmake .. -DCMAKE_CXX_FLAGS=-std=c++11 -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython2.7.so -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python2.7;
      fi

script:
    - make

notifications:
email: false
